### ISSUE TITLE
mqttClient connectError -2

### ISSUE THREAD

**Issue by K0I05** [n-elia/Arduino-Nano-33-IoT-Azure-DPS-with-SAS-tokens#1] opened 2022-01-15 16:48 UTC
Hello,

Thanks for posting this example.  I am using an Arduino NANO 33 IoT and able to connect to the Azure IoT Hub successfully via X.509 self-signed methodology.  I setup an app in IoT Central and created a device to sample your project, grabbed the primary key from the device 'connect' details, and generated the SAS token but for some reason there is an MQTT connect error of 'Connection Refused (-2)'.  

Are you able to offer direction to troubleshoot this problem?

Thanks

Eric

**Comment by n-elia** [comment] 2022-01-15 21:16
Hi!

I don't remember every detail of the connection with Azure Central very well, because I'm working with other assets since a year. I will still try to be helpful!

May you provide your sketch (taking care of masking your secrets)?

Did you add the Baltimore CA-root certificate to your WiFiNINA module? (It gets wiped out when you perform certain types of flashing)

I would also make a checklist of the needed parameters (addresses, tokens, topic names, ...).

Nicola

**Comment by n-elia** [comment] 2022-01-16 10:55
Also, let's check if you followed the [suggested procedure](https://docs.microsoft.com/en-us/azure/iot-central/core/concepts-get-connected#create-individual-enrollments) for connecting to IoT Central.
Have you selected "Individual enrollment" as the connection method, and "Shared access signature" (SAS) as the mechanism?
Did you put the correct ID scope, Device ID, and primary key into your scketch?

**Comment by K0I05** [comment] 2022-01-17 12:35
Thanks very much, Nicola.  The one step I didn't do was adding the Baltimore CA-root to the WiFiNINA module.  I tried this step in earlier attempts but not sure I was using the correct url: cacerts.digicert.com.  Its interesting that the WiFiNINA module connects to IoT Hub without adding the Baltimore CA-root certificate but will add it regardless provided the url I am using is correct.

In IoT Central I believe group enrolment is being used, under 'Administration->Device connection', there are three groups listed:

- SAS IoT Devices
- SAS IoT Edge Devices
- X509 IoT Devices (earlier attempt on your X.509 example)

All three entries reference the same ID scope.  Under 'Devices' there is one entry, this entry under 'Connect' details, the info was utilized to generate the SAS token via provided python script.  Authentication type for this device was left to default: Shared Access Signature.

Also, I am using your original sketch and the only changes made was to the 'secret.h' file as a test: figured it would be best to validate connectivity (step 1) before trying other things.

**Comment by n-elia** [comment] 2022-01-17 15:29
Hi,

since you have a problem connecting to the MQTT broker, let's start from the beginning.
You do need to use a secured connection to properly run this sketch. Let's ensure that the certificate is properly loaded. To add a certificate, you just need to follow [these](https://support.arduino.cc/hc/en-us/articles/360016119219-How-to-add-certificates-to-Wifi-Nina-Wifi-101-Modules-) steps. Please note that you do not need to provide the certificate itself; instead, the Arduino tool will automatically fetch the certificate by vising your target URI. For instance, to download the Azure Device Provisioning Service certificate, use this link: `global.azure-devices-provisioning.net:443`.

Please take this step carefully and then let me know if it works.

**Comment by K0I05** [comment] 2022-01-17 16:11
certificate was added:

1. loaded the WiFiNINA firmware updater sketch
2. added 'global.azure-devices-provisioning.net:443' to the list of domains
3. selected 'global.azure-devices-provisioning.net:443' entry and update stated successful
4. loaded the Azure DPS SAS sketch but getting the same error

**Comment by n-elia** [comment] 2022-01-17 16:44
Fine!

So, I'll assume that, since we're getting a "Connection refused" error, the problem is related to either the credentials (_username_, _password_) or the _registrationId_.

First of all, this repo refers to DPS. I took a look to the latest [docs](https://docs.microsoft.com/en-us/azure/iot-dps/iot-dps-mqtt-support#using-the-mqtt-protocol-directly-as-a-device) and it seems to me that parameters values in my sketch are still up to date for working with Azure DPS; feel free to check by yourself.

1. The sketch you're using works with Group Enrollment. Can you confirm that your IoT Central app is using SAS keys within an Enrollment Group? ([ref](https://docs.microsoft.com/en-us/azure/iot-central/core/concepts-get-connected#automatically-register-devices-that-use-sas-tokens))

2. Have you checked that your _registrationId_ is compliant to the rules stated in the [docs](https://docs.microsoft.com/en-us/azure/iot-dps/concepts-service#registration-id)?

3. Did you use the very same _scope ID_ and _registration ID_ when generating the SAS token? Have you tried with a brand new _registrationId_ (remembering to put it in the sketch, too)? (just to be sure against typos)

**Comment by n-elia** [comment] 2022-02-09 10:19
Hi @egionet, did you manage to solve your problem?

**Comment by n-elia** [comment] 2022-02-17 23:12
I am closing this issue because of no interactions. Feel free to reopen it if you will ever need.

**Closed as completed by n-elia** 2022-02-17 23:12 UTC

**Comment by K0I05** [comment] 2022-02-27 21:59
Thanks, Nicola.  I did find some errors and just haven't had time to retest.
